### ISSUE TITLE
Fatal error: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by Synchro** [ghost-town/grunt-init-assemble#11]
I'm trying out init-assemble, following the intro docs. After answering questions with almost all default answers, the initial build errors out with 'Fatal error: Arguments to path.join must be strings':

![screen shot 2013-12-24 at 11 10 56](https://f.cloud.github.com/assets/81561/1805482/c0102ca6-6c83-11e3-86f5-8ef9d46a8b35.png)

**Comment by jonschlinkert** [comment]
sorry, we're in the process of launching new docs and a complete refactor of assemble, there are some things that can (will) improve in the docs for sure. 

I also have a new version of this to push up, but we've mostly be advocating https://github.com/assemble/generator-assemble instead of grunt-init-assemble anyway. sorry for the issues

**Comment by jonschlinkert** [comment]
Done. This was bumped to 0.4.0, so you'll have to redownload. Please let me know if you have any issues. thanks!
